(()=>{var e={};e.id=571,e.ids=[571],e.modules={47849:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external")},72934:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external.js")},55403:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external")},54580:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external.js")},94749:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external")},45869:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},82361:e=>{"use strict";e.exports=require("events")},13685:e=>{"use strict";e.exports=require("http")},95687:e=>{"use strict";e.exports=require("https")},71017:e=>{"use strict";e.exports=require("path")},57310:e=>{"use strict";e.exports=require("url")},73837:e=>{"use strict";e.exports=require("util")},92381:(e,t,r)=>{"use strict";r.r(t),r.d(t,{GlobalError:()=>i.a,__next_app__:()=>u,originalPathname:()=>p,pages:()=>d,routeModule:()=>m,tree:()=>c});var n=r(50482),s=r(69108),a=r(62563),i=r.n(a),l=r(68300),o={};for(let e in l)0>["default","tree","pages","GlobalError","originalPathname","__next_app__","routeModule"].indexOf(e)&&(o[e]=()=>l[e]);r.d(t,o);let c=["",{children:["timeline",{children:["__PAGE__",{},{page:[()=>Promise.resolve().then(r.bind(r,69079)),"/home/runner/work/portfolio/portfolio/nextjs/app/timeline/page.tsx"]}]},{metadata:{icon:[async e=>(await Promise.resolve().then(r.bind(r,57481))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}]},{layout:[()=>Promise.resolve().then(r.bind(r,19097)),"/home/runner/work/portfolio/portfolio/nextjs/app/layout.tsx"],"not-found":[()=>Promise.resolve().then(r.t.bind(r,69361,23)),"next/dist/client/components/not-found-error"],metadata:{icon:[async e=>(await Promise.resolve().then(r.bind(r,57481))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}],d=["/home/runner/work/portfolio/portfolio/nextjs/app/timeline/page.tsx"],p="/timeline/page",u={require:r,loadChunk:()=>Promise.resolve()},m=new n.AppPageRouteModule({definition:{kind:s.x.APP_PAGE,page:"/timeline/page",pathname:"/timeline",bundlePath:"",filename:"",appPaths:[]},userland:{loaderTree:c}})},28713:(e,t,r)=>{let n={"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de":()=>Promise.resolve().then(r.bind(r,36915)).then(e=>e.revalidateRootLayout)};async function s(e,...t){return(await n[e]()).apply(null,t)}e.exports={"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de":s.bind(null,"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de")}},46563:(e,t,r)=>{Promise.resolve().then(r.t.bind(r,61476,23))},7825:(e,t,r)=>{Promise.resolve().then(r.t.bind(r,2583,23)),Promise.resolve().then(r.t.bind(r,26840,23)),Promise.resolve().then(r.t.bind(r,38771,23)),Promise.resolve().then(r.t.bind(r,13225,23)),Promise.resolve().then(r.t.bind(r,9295,23)),Promise.resolve().then(r.t.bind(r,43982,23))},75147:(e,t,r)=>{Promise.resolve().then(r.bind(r,1156)),Promise.resolve().then(r.t.bind(r,31900,23))},19097:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>c,metadata:()=>o});var n=r(25036),s=r(24260),a=r.n(s);r(67272);var i=r(16274);let l=()=>n.jsx("nav",{className:"navbar",children:(0,n.jsxs)("div",{className:"navbar-links",children:[n.jsx(i.default,{href:"/",className:"navbar-link",children:"Home"}),n.jsx(i.default,{href:"/timeline",className:"navbar-link",children:"Experience"}),n.jsx(i.default,{href:"/skills",className:"navbar-link",children:"Skills"}),n.jsx(i.default,{href:"/projects",className:"navbar-link",children:"Projects"}),n.jsx(i.default,{href:"/awards",className:"navbar-link",children:"Awards"}),n.jsx(i.default,{href:"/interests",className:"navbar-link",children:"Interests"}),n.jsx(i.default,{href:"/contact",className:"navbar-link",children:"Contact"})]})}),o={title:"Marcel Kornblum",description:"Generated by create next app"};function c({children:e}){return n.jsx("html",{lang:"en",className:a().variable,children:(0,n.jsxs)("body",{className:"body",children:[n.jsx(l,{}),e]})})}},69079:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>o});var n=r(25036),s=r(11514);r(40002);var a=r(2813),i=r(73674);let l=({experiences:e})=>n.jsx("div",{className:"timeline",children:e.map((e,t)=>n.jsx("div",{className:"timeline-item",children:(0,n.jsxs)("div",{className:"timeline-item-content",children:[(0,n.jsxs)("div",{className:"timeline-item-header",children:[e.company?.logo&&n.jsx(a.default,{src:e.company.logo.asset.url,alt:e.company.name,width:50,height:50}),n.jsx("h3",{className:"font-bold",children:e.role}),n.jsx("a",{href:e.company?.link,target:"_blank",rel:"noopener noreferrer",children:e.company?.name})]}),(0,n.jsxs)("div",{className:"timeline-item-date",children:[(0,i.WU)(new Date(e.start),"MMM yyyy")," -"," ",e.end?(0,i.WU)(new Date(e.end),"MMM yyyy"):"Present"]}),n.jsx("div",{className:"timeline-item-details",children:e.details?.map((e,t)=>n.jsx("p",{children:e.children[0].text},t))})]})},e._id))});async function o(){let e=await (0,s.E$)();return n.jsx("main",{children:n.jsx(l,{experiences:e})})}},11514:(e,t,r)=>{"use strict";r.d(t,{R0:()=>l,HQ:()=>d,vS:()=>o,E$:()=>i,gv:()=>p,mW:()=>a,SM:()=>c});let n=(0,r(74737).eI)({projectId:"ctyiavss",dataset:"production",apiVersion:"2023-05-03",useCdn:!0});var s=r(97433);async function a(){return n.fetch(s.Z`
        *[_type == "project"] {
            _id,
            name,
            date,
            image,
            details,
            role-> {
                role
            }
        }
    `)}async function i(){return n.fetch(s.Z`
        *[_type == "experience"] | order(start desc) {
            _id,
            role,
            start,
            end,
            details,
            company->{
                name,
                logo,
                link
            },
            slug
        }
    `)}async function l(){return n.fetch(s.Z`*[_type == "about"]`)}async function o(){return n.fetch(s.Z`*[_type == "contact"]`)}async function c(){return n.fetch(s.Z`
        *[_type == "skill"] {
            _id,
            name,
            details,
            evidence[] {
                point,
                role-> {
                    _id,
                    role,
                    start,
                    end,
                    slug
                }
            }
        }
    `)}async function d(){return n.fetch(s.Z`
        *[_type == "award"] {
            _id,
            name,
            details,
            role-> {
                role
            }
        }
    `)}async function p(){return n.fetch(s.Z`
        *[_type == "passion"] {
            _id,
            name,
            details
        }
    `)}},57481:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>s});var n=r(70337);let s=e=>[{type:"image/x-icon",sizes:"16x16",url:(0,n.fillMetadataSegment)(".",e.params,"favicon.ico")+""}]},67272:()=>{}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),n=t.X(0,[638,565,435,674,861],()=>r(92381));module.exports=n})();