(()=>{var e={};e.id=327,e.ids=[327],e.modules={47849:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external")},72934:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external.js")},55403:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external")},54580:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external.js")},94749:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external")},45869:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},82361:e=>{"use strict";e.exports=require("events")},13685:e=>{"use strict";e.exports=require("http")},95687:e=>{"use strict";e.exports=require("https")},71017:e=>{"use strict";e.exports=require("path")},57310:e=>{"use strict";e.exports=require("url")},73837:e=>{"use strict";e.exports=require("util")},3577:(e,t,r)=>{"use strict";r.r(t),r.d(t,{GlobalError:()=>i.a,__next_app__:()=>p,originalPathname:()=>u,pages:()=>d,routeModule:()=>m,tree:()=>c});var a=r(50482),n=r(69108),s=r(62563),i=r.n(s),o=r(68300),l={};for(let e in o)0>["default","tree","pages","GlobalError","originalPathname","__next_app__","routeModule"].indexOf(e)&&(l[e]=()=>o[e]);r.d(t,l);let c=["",{children:["contact",{children:["__PAGE__",{},{page:[()=>Promise.resolve().then(r.bind(r,57155)),"/home/runner/work/portfolio/portfolio/nextjs/app/contact/page.tsx"]}]},{metadata:{icon:[async e=>(await Promise.resolve().then(r.bind(r,57481))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}]},{layout:[()=>Promise.resolve().then(r.bind(r,19097)),"/home/runner/work/portfolio/portfolio/nextjs/app/layout.tsx"],"not-found":[()=>Promise.resolve().then(r.t.bind(r,69361,23)),"next/dist/client/components/not-found-error"],metadata:{icon:[async e=>(await Promise.resolve().then(r.bind(r,57481))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}],d=["/home/runner/work/portfolio/portfolio/nextjs/app/contact/page.tsx"],u="/contact/page",p={require:r,loadChunk:()=>Promise.resolve()},m=new a.AppPageRouteModule({definition:{kind:n.x.APP_PAGE,page:"/contact/page",pathname:"/contact",bundlePath:"",filename:"",appPaths:[]},userland:{loaderTree:c}})},28713:(e,t,r)=>{let a={"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de":()=>Promise.resolve().then(r.bind(r,36915)).then(e=>e.revalidateRootLayout)};async function n(e,...t){return(await a[e]()).apply(null,t)}e.exports={"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de":n.bind(null,"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de")}},46563:(e,t,r)=>{Promise.resolve().then(r.t.bind(r,61476,23))},7825:(e,t,r)=>{Promise.resolve().then(r.t.bind(r,2583,23)),Promise.resolve().then(r.t.bind(r,26840,23)),Promise.resolve().then(r.t.bind(r,38771,23)),Promise.resolve().then(r.t.bind(r,13225,23)),Promise.resolve().then(r.t.bind(r,9295,23)),Promise.resolve().then(r.t.bind(r,43982,23))},16731:(e,t,r)=>{Promise.resolve().then(r.bind(r,1156))},57155:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>o});var a=r(25036),n=r(11514);let s=({about:e})=>(0,a.jsxs)("div",{className:"about",children:[a.jsx("h2",{children:e.name}),a.jsx("div",{className:"about-details",children:e.details.map((e,t)=>a.jsx("p",{children:e.children[0].text},t))})]}),i=({contact:e})=>a.jsx("div",{className:"contact-item",children:a.jsx("a",{href:e.link,target:"_blank",rel:"noopener noreferrer",children:e.display})});async function o(){let e=await (0,n.R0)(),t=await (0,n.vS)();return(0,a.jsxs)("main",{className:"contact",children:[a.jsx("h1",{children:"Contact"}),a.jsx("div",{className:"contact-info",children:t.map(e=>a.jsx(i,{contact:e},e._id))}),a.jsx("div",{className:"about-info",children:e.map(e=>a.jsx(s,{about:e},e._id))})]})}},19097:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>c,metadata:()=>l});var a=r(25036),n=r(24260),s=r.n(n);r(67272);var i=r(16274);let o=()=>a.jsx("nav",{className:"navbar",children:(0,a.jsxs)("div",{className:"navbar-links",children:[a.jsx(i.default,{href:"/",className:"navbar-link",children:"Home"}),a.jsx(i.default,{href:"/timeline",className:"navbar-link",children:"Experience"}),a.jsx(i.default,{href:"/skills",className:"navbar-link",children:"Skills"}),a.jsx(i.default,{href:"/projects",className:"navbar-link",children:"Projects"}),a.jsx(i.default,{href:"/awards",className:"navbar-link",children:"Awards"}),a.jsx(i.default,{href:"/interests",className:"navbar-link",children:"Interests"}),a.jsx(i.default,{href:"/contact",className:"navbar-link",children:"Contact"})]})}),l={title:"Marcel Kornblum",description:"Generated by create next app"};function c({children:e}){return a.jsx("html",{lang:"en",className:s().variable,children:(0,a.jsxs)("body",{className:"body",children:[a.jsx(o,{}),e]})})}},11514:(e,t,r)=>{"use strict";r.d(t,{R0:()=>o,HQ:()=>d,vS:()=>l,E$:()=>i,gv:()=>u,mW:()=>s,SM:()=>c});let a=(0,r(74737).eI)({projectId:"ctyiavss",dataset:"production",apiVersion:"2023-05-03",useCdn:!0});var n=r(97433);async function s(){return a.fetch(n.Z`
        *[_type == "project"] {
            _id,
            name,
            date,
            image,
            details,
            role-> {
                role
            }
        }
    `)}async function i(){return a.fetch(n.Z`
        *[_type == "experience"] | order(start desc) {
            _id,
            role,
            start,
            end,
            details,
            company->{
                name,
                logo,
                link
            },
            slug
        }
    `)}async function o(){return a.fetch(n.Z`*[_type == "about"]`)}async function l(){return a.fetch(n.Z`*[_type == "contact"]`)}async function c(){return a.fetch(n.Z`
        *[_type == "skill"] {
            _id,
            name,
            details,
            evidence[] {
                point,
                role-> {
                    _id,
                    role,
                    start,
                    end,
                    slug
                }
            }
        }
    `)}async function d(){return a.fetch(n.Z`
        *[_type == "award"] {
            _id,
            name,
            details,
            role-> {
                role
            }
        }
    `)}async function u(){return a.fetch(n.Z`
        *[_type == "passion"] {
            _id,
            name,
            details
        }
    `)}},57481:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>n});var a=r(70337);let n=e=>[{type:"image/x-icon",sizes:"16x16",url:(0,a.fillMetadataSegment)(".",e.params,"favicon.ico")+""}]},67272:()=>{}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[638,565,435],()=>r(3577));module.exports=a})();