(()=>{var e={};e.id=931,e.ids=[931],e.modules={47849:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external")},72934:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external.js")},55403:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external")},54580:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external.js")},94749:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external")},45869:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},82361:e=>{"use strict";e.exports=require("events")},13685:e=>{"use strict";e.exports=require("http")},95687:e=>{"use strict";e.exports=require("https")},71017:e=>{"use strict";e.exports=require("path")},57310:e=>{"use strict";e.exports=require("url")},73837:e=>{"use strict";e.exports=require("util")},65225:(e,t,r)=>{"use strict";r.r(t),r.d(t,{GlobalError:()=>i.a,__next_app__:()=>p,originalPathname:()=>u,pages:()=>d,routeModule:()=>m,tree:()=>c});var s=r(50482),n=r(69108),a=r(62563),i=r.n(a),l=r(68300),o={};for(let e in l)0>["default","tree","pages","GlobalError","originalPathname","__next_app__","routeModule"].indexOf(e)&&(o[e]=()=>l[e]);r.d(t,o);let c=["",{children:["__PAGE__",{},{page:[()=>Promise.resolve().then(r.bind(r,70751)),"/home/runner/work/portfolio/portfolio/nextjs/app/page.tsx"],metadata:{icon:[async e=>(await Promise.resolve().then(r.bind(r,57481))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}]},{layout:[()=>Promise.resolve().then(r.bind(r,19097)),"/home/runner/work/portfolio/portfolio/nextjs/app/layout.tsx"],"not-found":[()=>Promise.resolve().then(r.t.bind(r,69361,23)),"next/dist/client/components/not-found-error"],metadata:{icon:[async e=>(await Promise.resolve().then(r.bind(r,57481))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}],d=["/home/runner/work/portfolio/portfolio/nextjs/app/page.tsx"],u="/page",p={require:r,loadChunk:()=>Promise.resolve()},m=new s.AppPageRouteModule({definition:{kind:n.x.APP_PAGE,page:"/page",pathname:"/",bundlePath:"",filename:"",appPaths:[]},userland:{loaderTree:c}})},28713:(e,t,r)=>{let s={"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de":()=>Promise.resolve().then(r.bind(r,36915)).then(e=>e.revalidateRootLayout)};async function n(e,...t){return(await s[e]()).apply(null,t)}e.exports={"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de":n.bind(null,"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de")}},46563:(e,t,r)=>{Promise.resolve().then(r.t.bind(r,61476,23))},7825:(e,t,r)=>{Promise.resolve().then(r.t.bind(r,2583,23)),Promise.resolve().then(r.t.bind(r,26840,23)),Promise.resolve().then(r.t.bind(r,38771,23)),Promise.resolve().then(r.t.bind(r,13225,23)),Promise.resolve().then(r.t.bind(r,9295,23)),Promise.resolve().then(r.t.bind(r,43982,23))},24469:(e,t,r)=>{Promise.resolve().then(r.bind(r,1156)),Promise.resolve().then(r.t.bind(r,61476,23))},19097:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>c,metadata:()=>o});var s=r(25036),n=r(24260),a=r.n(n);r(67272);var i=r(16274);let l=()=>s.jsx("nav",{className:"navbar",children:(0,s.jsxs)("div",{className:"navbar-links",children:[s.jsx(i.default,{href:"/",className:"navbar-link",children:"Home"}),s.jsx(i.default,{href:"/timeline",className:"navbar-link",children:"Experience"}),s.jsx(i.default,{href:"/skills",className:"navbar-link",children:"Skills"}),s.jsx(i.default,{href:"/projects",className:"navbar-link",children:"Projects"}),s.jsx(i.default,{href:"/awards",className:"navbar-link",children:"Awards"}),s.jsx(i.default,{href:"/interests",className:"navbar-link",children:"Interests"}),s.jsx(i.default,{href:"/contact",className:"navbar-link",children:"Contact"})]})}),o={title:"Marcel Kornblum",description:"Generated by create next app"};function c({children:e}){return s.jsx("html",{lang:"en",className:a().variable,children:(0,s.jsxs)("body",{className:"body",children:[s.jsx(l,{}),e]})})}},70751:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>i});var s=r(25036),n=r(11514),a=r(16274);async function i(){let e=await (0,n.R0)(),t=await (0,n.vS)();return(0,s.jsxs)("main",{className:"home",children:[(0,s.jsxs)("div",{className:"home-header",children:[s.jsx("h1",{children:"Marcel Kornblum"}),e.map(e=>s.jsx("div",{className:"home-about",children:s.jsx("h2",{children:e.name})},e._id))]}),s.jsx("div",{className:"home-contact",children:t.map(e=>"email"===e.type?s.jsx("div",{className:"home-contact-item",children:s.jsx("a",{href:e.link,target:"_blank",rel:"noopener noreferrer",children:e.display})},e._id):null)}),(0,s.jsxs)("div",{className:"home-links",children:[s.jsx(a.default,{href:"/timeline",className:"home-timeline-link",children:"Experience"}),s.jsx(a.default,{href:"/skills",className:"home-skills-link",children:"Skills"})]})]})}},11514:(e,t,r)=>{"use strict";r.d(t,{R0:()=>l,HQ:()=>d,vS:()=>o,E$:()=>i,gv:()=>u,mW:()=>a,SM:()=>c});let s=(0,r(74737).eI)({projectId:"ctyiavss",dataset:"production",apiVersion:"2023-05-03",useCdn:!0});var n=r(97433);async function a(){return s.fetch(n.Z`
        *[_type == "project"] {
            _id,
            name,
            date,
            image,
            details,
            role-> {
                role
            }
        }
    `)}async function i(){return s.fetch(n.Z`
        *[_type == "experience"] | order(start desc) {
            _id,
            role,
            start,
            end,
            details,
            company->{
                name,
                logo,
                link
            },
            slug
        }
    `)}async function l(){return s.fetch(n.Z`*[_type == "about"]`)}async function o(){return s.fetch(n.Z`*[_type == "contact"]`)}async function c(){return s.fetch(n.Z`
        *[_type == "skill"] {
            _id,
            name,
            details,
            evidence[] {
                point,
                role-> {
                    _id,
                    role,
                    start,
                    end,
                    slug
                }
            }
        }
    `)}async function d(){return s.fetch(n.Z`
        *[_type == "award"] {
            _id,
            name,
            details,
            role-> {
                role
            }
        }
    `)}async function u(){return s.fetch(n.Z`
        *[_type == "passion"] {
            _id,
            name,
            details
        }
    `)}},57481:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>n});var s=r(70337);let n=e=>[{type:"image/x-icon",sizes:"16x16",url:(0,s.fillMetadataSegment)(".",e.params,"favicon.ico")+""}]},67272:()=>{}};var t=require("../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[638,565,435],()=>r(65225));module.exports=s})();