(()=>{var e={};e.id=274,e.ids=[274],e.modules={47849:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external")},72934:e=>{"use strict";e.exports=require("next/dist/client/components/action-async-storage.external.js")},55403:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external")},54580:e=>{"use strict";e.exports=require("next/dist/client/components/request-async-storage.external.js")},94749:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external")},45869:e=>{"use strict";e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},82361:e=>{"use strict";e.exports=require("events")},13685:e=>{"use strict";e.exports=require("http")},95687:e=>{"use strict";e.exports=require("https")},71017:e=>{"use strict";e.exports=require("path")},57310:e=>{"use strict";e.exports=require("url")},73837:e=>{"use strict";e.exports=require("util")},66868:(e,t,s)=>{"use strict";s.r(t),s.d(t,{GlobalError:()=>i.a,__next_app__:()=>u,originalPathname:()=>p,pages:()=>d,routeModule:()=>m,tree:()=>c});var r=s(50482),n=s(69108),a=s(62563),i=s.n(a),o=s(68300),l={};for(let e in o)0>["default","tree","pages","GlobalError","originalPathname","__next_app__","routeModule"].indexOf(e)&&(l[e]=()=>o[e]);s.d(t,l);let c=["",{children:["interests",{children:["__PAGE__",{},{page:[()=>Promise.resolve().then(s.bind(s,33242)),"/home/runner/work/portfolio/portfolio/nextjs/app/interests/page.tsx"]}]},{metadata:{icon:[async e=>(await Promise.resolve().then(s.bind(s,15053))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}]},{layout:[()=>Promise.resolve().then(s.bind(s,19097)),"/home/runner/work/portfolio/portfolio/nextjs/app/layout.tsx"],"not-found":[()=>Promise.resolve().then(s.t.bind(s,69361,23)),"next/dist/client/components/not-found-error"],metadata:{icon:[async e=>(await Promise.resolve().then(s.bind(s,15053))).default(e)],apple:[],openGraph:[],twitter:[],manifest:void 0}}],d=["/home/runner/work/portfolio/portfolio/nextjs/app/interests/page.tsx"],p="/interests/page",u={require:s,loadChunk:()=>Promise.resolve()},m=new r.AppPageRouteModule({definition:{kind:n.x.APP_PAGE,page:"/interests/page",pathname:"/interests",bundlePath:"",filename:"",appPaths:[]},userland:{loaderTree:c}})},28713:(e,t,s)=>{let r={"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de":()=>Promise.resolve().then(s.bind(s,36915)).then(e=>e.revalidateRootLayout)};async function n(e,...t){return(await r[e]()).apply(null,t)}e.exports={"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de":n.bind(null,"96ed5e9b5cfd2f2f80a8e27eb31a4f564e9a77de")}},46563:(e,t,s)=>{Promise.resolve().then(s.t.bind(s,61476,23))},7825:(e,t,s)=>{Promise.resolve().then(s.t.bind(s,2583,23)),Promise.resolve().then(s.t.bind(s,26840,23)),Promise.resolve().then(s.t.bind(s,38771,23)),Promise.resolve().then(s.t.bind(s,13225,23)),Promise.resolve().then(s.t.bind(s,9295,23)),Promise.resolve().then(s.t.bind(s,43982,23))},16731:(e,t,s)=>{Promise.resolve().then(s.bind(s,1156))},33242:(e,t,s)=>{"use strict";s.r(t),s.d(t,{default:()=>i});var r=s(25036),n=s(11514);let a=({passion:e})=>(0,r.jsxs)("div",{className:"passion",children:[r.jsx("h2",{children:e.name}),r.jsx("div",{className:"passion-details",children:e.details.map((e,t)=>r.jsx("p",{children:e.children[0].text},t))})]});async function i(){let e=await (0,n.gv)();return(0,r.jsxs)("main",{className:"passions",children:[r.jsx("h1",{children:"Interests, hobbies and passions"}),r.jsx("div",{className:"passions-list",children:e.map(e=>r.jsx(a,{passion:e},e._id))})]})}},19097:(e,t,s)=>{"use strict";s.r(t),s.d(t,{default:()=>c,metadata:()=>l});var r=s(25036),n=s(24260),a=s.n(n);s(67272);var i=s(16274);let o=()=>r.jsx("nav",{className:"navbar",children:(0,r.jsxs)("div",{className:"navbar-links",children:[r.jsx(i.default,{href:"/",className:"navbar-link",children:"Home"}),r.jsx(i.default,{href:"/timeline",className:"navbar-link",children:"Experience"}),r.jsx(i.default,{href:"/skills",className:"navbar-link",children:"Skills"}),r.jsx(i.default,{href:"/projects",className:"navbar-link",children:"Projects"}),r.jsx(i.default,{href:"/awards",className:"navbar-link",children:"Awards"}),r.jsx(i.default,{href:"/interests",className:"navbar-link",children:"Interests"}),r.jsx(i.default,{href:"/contact",className:"navbar-link",children:"Contact"})]})}),l={title:"Marcel Kornblum",description:"Generated by create next app"};function c({children:e}){return r.jsx("html",{lang:"en",className:a().variable,children:(0,r.jsxs)("body",{className:"body",children:[r.jsx(o,{}),e]})})}},11514:(e,t,s)=>{"use strict";s.d(t,{R0:()=>o,HQ:()=>d,vS:()=>l,E$:()=>i,gv:()=>p,mW:()=>a,SM:()=>c});let r=(0,s(74737).eI)({projectId:"ctyiavss",dataset:"production",apiVersion:"2023-05-03",useCdn:!0});var n=s(97433);async function a(){return r.fetch(n.Z`
        *[_type == "project"] {
            _id,
            name,
            date,
            image,
            details,
            role-> {
                role
            }
        }
    `)}async function i(){return r.fetch(n.Z`
        *[_type == "experience"] | order(start desc) {
            _id,
            role,
            start,
            end,
            details,
            company->{
                name,
                logo,
                link
            },
            slug
        }
    `)}async function o(){return r.fetch(n.Z`*[_type == "about"]`)}async function l(){return r.fetch(n.Z`*[_type == "contact"]`)}async function c(){return r.fetch(n.Z`
        *[_type == "skill"] {
            _id,
            name,
            details,
            evidence[] {
                point,
                role-> {
                    _id,
                    role,
                    start,
                    end,
                    slug
                }
            }
        }
    `)}async function d(){return r.fetch(n.Z`
        *[_type == "award"] {
            _id,
            name,
            details,
            role-> {
                role
            }
        }
    `)}async function p(){return r.fetch(n.Z`
        *[_type == "passion"] {
            _id,
            name,
            details
        }
    `)}},15053:(e,t,s)=>{"use strict";s.r(t),s.d(t,{default:()=>n});var r=s(70337);let n=e=>[{type:"image/x-icon",sizes:"16x16",url:(0,r.fillMetadataSegment)("/portfolio",e.params,"favicon.ico")+""}]},67272:()=>{}};var t=require("../../webpack-runtime.js");t.C(e);var s=e=>t(t.s=e),r=t.X(0,[638,565,435],()=>s(66868));module.exports=r})();