import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Marcel Kornblum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.variable}>
      <body className="body">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
